### ISSUE TITLE
#api get result: why do we need idInitiatingParty?

### ISSUE THREAD

**Issue by strathink** [strathink/myb#12]
TransactionID must be unique and contructed by the Gateway

**Comment by strathink** [comment]
As you said the transactionID is unique and created by the Gateway

**Comment by strathink** [comment]
If you need to live it than you need to add it in the paymentInitiationResponse

**Comment by cwbi-developer** [comment]
The idInitiatingParty is necessary for checking the initiating party's certificate.

**Comment by strathink** [comment]
Ok but should it be it in the response as well in that case?
