### ISSUE TITLE
#dataelement: do you allow InititiatingPartyID with same value?

### ISSUE THREAD

**Issue by strathink** [strathink/myb#13]

**Comment by cwbi-developer** [comment]
#13 No, InititiatingPartyID must be unique.

**Comment by strathink** [comment]
Thank you. Closed

Tarik
________________________________
De : cwbi-developer <notifications@github.com>
Envoyé : Friday, March 13, 2020 5:45:49 PM
À : strathink/myb <myb@noreply.github.com>
Cc : Tarik Zerkti <t.zerkti@preta.eu>; Author <author@noreply.github.com>
Objet : Re: [strathink/myb] #dataelement: do you allow InititiatingPartyID with same value? (#13)


#13<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fstrathink%2Fmyb%2Fissues%2F13&data=02%7C01%7Ct.zerkti%40preta.eu%7C2102810236fd494ab75808d7c76dfd6a%7Ca716661474044f3494666fb44a5d2368%7C0%7C0%7C637197147520926058&sdata=tQgOac%2FZPlSAPkDtGZJyoqXRb%2FE3k5%2Fp7cicze%2BrR8s%3D&reserved=0> No, InititiatingPartyID must be unique.
